// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	UserName string `json:"userName"`
	Money    int    `json:"money"`
}

type CreateAccountInput struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type CreateAccountResponse struct {
	Success      bool    `json:"success"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
